# Dockerfile
#
# Builds an image that serves app.py (the FastAPI churn prediction API)
# with uvicorn, using uv + pyproject.toml/uv.lock for dependency install.
#
# Build:
#   docker build -t churn-api .
#
# Run (mount the artifacts produced by save_model.py — the .onnx model,
# scaler.joblib, and feature_names.json — rather than baking them into the
# image, so you can swap models without rebuilding):
#   docker run -p 8000:8000 -v "$(pwd)/artifacts:/app/artifacts" churn-api
#
# Then open http://localhost:8000/docs for the interactive API docs.

FROM python:3.11-slim

WORKDIR /app

# libgomp1 is required at runtime by LightGBM/XGBoost's OpenMP-based
# training and inference code. curl is used by the HEALTHCHECK below.
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 curl \
    && rm -rf /var/lib/apt/lists/*

# Pull the uv binary from Astral's official image rather than pip-installing
# it, so it isn't tangled up with this project's own dependency resolution.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install Python dependencies first so this layer is cached across code
# changes (only re-runs when pyproject.toml/uv.lock change).
COPY pyproject.toml uv.lock README.md ./
RUN uv sync --frozen --no-dev --no-install-project

# Application code and config.
COPY UI.html ./
COPY src/ ./src/
COPY configs ./configs

# Now install the project itself (fast — deps are already cached above).
RUN uv sync --frozen --no-dev

# Model artifacts (the .onnx file, scaler.joblib, feature_names.json) are
# expected to be provided at runtime via a volume mount at /app/artifacts
# (see the `docker run -v` example above), since they're generated by
# save_model.py and change independently of the application code. To bake
# a specific model into the image instead, uncomment the next line:
# COPY artifacts ./artifacts

EXPOSE 8000

# Fails the container's health status if /health stops responding, so an
# orchestrator (Docker, Compose, Kubernetes) can detect and restart it.
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

# `uv run` executes inside the .venv uv created during `uv sync`, so
# gunicorn is found without needing it (or the venv) on PATH separately.
CMD ["uv", "run", "gunicorn", "app:app", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]